### ISSUE TITLE
Problem activating Phobos in Blender

### ISSUE THREAD

**Issue by AmineCybernetics** [rock-simulation/phobos#111]
Hi all,

I followed the instruction in the tutorial to install phobos in blender. I am on ubuntu 14.04 and I am using blender 2.71. Wenn I tried to activate phobos in blender I get the error:
Traceback (most recent call last):
File "usr/share/blnder/2.71/scripts/addons/phobos/__init__.py", line 129, in <module>
 phobos.defs.updateDefs(os.path.dirname(__file__)+"/definitions")
AttributeError: 'module' object has no attribute 'defs'

I would be nice if you can help me fixing it :)

thanks in advance

**Comment by kavonszadkowski** [comment]
I suspect you're working with the current master rather than the last release 0.7?
If so, please try the last release instead. There is a lot of work currently being done on master, see [Announcements](https://github.com/rock-simulation/phobos#announcements).

**Comment by AmineCybernetics** [comment]
That solved the issue thanks!

**Comment by kavonszadkowski** [comment]
Great to hear, hope you'll have a smoother run from here.

**Comment by Leocorp** [comment]
hello, I just cloned the master (0.7) but I am still facing this issue "phobos has no attributes defs"
I'm working on Ubuntu 16.04, Blender 2.76b. Any help would be appreciated.
